kheer_new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('office/', include('office.urls')),
    path('cases/', include('cases.urls')),
    path('user/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name='home-page'),
    path('about', views.about_page, name='about-page'),
    path('contact', views.contact, name='contact-page'),
    path('faq-questions', views.faq_question, name='faq'),
    path('ksa-2030', views.ksa_2030, name='ksa2030'),
    path('roaya', views.roaya_message, name='roaya'),
    path('tamkeen', views.tamkeen, name='tamkeen'),
    path('green-circle', views.green_circle, name='green-circle'),
    path('pernamg', views.pernamg, name='pernamg'),
    path('effect', views.effect, name='effect'),
    path('training', views.training, name='training'),
    path('ramadan', views.ramadan, name='ramdan'),
    path('reports', views.reports, name='reports'),
    path('shop-ksa', views.ksa_shop, name='shop-ksa'),
    path('takafel', views.takafel, name='takafel'),
    path('who', views.who_page, name='who'),

]

office/urls.py
from django.urls import path
from office import views

urlpatterns = [
    path('home-employee', views.home_employee, name='home-employee'),
    path('get-found-emp-info', views.get_emp_found_info, name='get-found-emp-info'),
    path('create/needy', views.create_needy, name='create-needy'),
    path('create/needy/ajax', views.create_neeedy_ajax, name='create-needy-ajax'),
    path('needy/list', views.needy_list, name='needy-list'),
    path('needy/detail/<int:pk>', views.needy_detial, name='needy-detail'),
    path('needy/delete', views.delete_needy, name='needy-delete'),
    path('found/delete', views.delete_found, name='found-delete'),
    path('found/detail/<int:pk>', views.found_detial, name='found-detail'),
    path('found/list', views.found_list, name='found-list'),
    path('enable/list', views.enable_list, name='enable-list'),
    path('found/add', views.add_foundation, name='add-found'),
    path('provider/add', views.add_provider, name='add-provider'),
    path('provider/list', views.provider_list, name='provider-list'),
    path('provider/delete', views.provider_delete, name='provider-delete'),
    path('employee/home', views.home_emp, name='home-emp'),
    path('course/add', views.add_course, name='add-course'),
    path('needy/search/<int:pk>', views.search_needy, name='search-needy'),
    path('needy/search/dash', views.search_needy_dash, name='search-needy-dash'),
    path('cases/list', views.cases_list, name='cases-list'),
    path('tamkeen/list', views.tamkeen_money, name='tamkeen-list'),
    path('add/bag', views.add_course_bag, name='add-bag'),
    path('pay/bag/<int:pk>', views.bag_payment, name='pay-bag'),
    path('bag/list/<int:pk>', views.bag_list, name='bag-list'),
    path('add/pay/ticket', views.add_pay_ticket, name='pay-ticket'),
    path('add/bag/cer', views.add_bag_cer, name='add-bag-cer'),
    path('takafel/type', views.takafel_type, name='new-takafel-case-page'),
    path('takafel/type/<int:pk>', views.takafel_type_page, name='takafel-type-page'),
    path('add/greenparticipant', views.add_green_participant, name='add-green-participant'),
    path('found/bags', views.found_bags, name='found-bags'),
    path('courses/search/<int:pk>', views.search_tamkeen_course, name='course-search'),
    path('<int:pk>', views.needy_pay, name='needy-payment'),

]

office/models.py
from django.db import models
from accounts.models import User
from datetime import date


class Dependency(models.Model):
    GENDER_CHOICES = (
        ('M', 'ذكر'),
        ('F', 'أنثى'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, verbose_name='النوع')
    STAGE_CHOICES = (
        ('التمهيدى', 'التمهيدى'),
        ('الأبتدائى', 'الأبتدائى'),
        ('الأعدادى', 'الأعدادى'),
        ('الثانوى', 'الثانوى'),
        ('الجامعه', 'الجامعه'),
    )
    stage = models.CharField(max_length=255, choices=STAGE_CHOICES, verbose_name='المرحله')
    age = models.SmallIntegerField(null=True, verbose_name='العمر')
    name = models.CharField(null=True, max_length=255, verbose_name='الأسم')

    def __str__(self):
        return self.name


class Needy(models.Model):
    name = models.CharField(max_length=255, null=True, verbose_name='اسم الحاله')
    HOME_CHOICES = (
        ('ملك', 'ملك'),
        ('إيجار', 'إيجار'),
        ('أخرى', 'أخرى'),

    )
    CASES_CHOICES = (
        (1, 'دعم الكهرباء'),
        (2, 'دعم الغذاء'),
        (3, 'دعم التعليم'),
        (4, 'دعم الماء'),
        (5, 'دعم الصحة'),
        (6, 'دعم اﻷيجار'),

    )
    details = models.TextField(blank=True, null=True, verbose_name='عرض الحاله')
    home = models.CharField(null=True, max_length=255, choices=HOME_CHOICES, verbose_name='السكن')
    national_id = models.CharField(unique=True, max_length=255, null=True, verbose_name='رقم الهويه')
    phone = models.CharField(max_length=255, null=True, verbose_name='الجوال')
    parent = models.CharField(max_length=255, null=True, verbose_name='العائل')
    job = models.CharField(max_length=255, null=True, verbose_name='المهنه')

    SOURCE_CHOICES = (
        ('راتب شهري', 'راتب شهري'),
        ('ضمان اجتماعي', 'ضمان اجتماعي'),
        ('حساب مواطن', 'حساب مواطن'),
        ('اخرى ', 'اخرى '),

    )
    source_income = models.CharField(null=True, max_length=255, choices=SOURCE_CHOICES, verbose_name='مصدر الدخل')
    dependencies = models.ManyToManyField(Dependency, verbose_name='الاطفال')
    HEALTH_STATUS = (
        ('مريض', 'مريض'), ('حالة حرجة', 'حالة حرجة'), ('صحة جيدة', 'صحة جيدة'),
    )
    health_status = models.CharField(null=True, max_length=255, choices=HEALTH_STATUS, verbose_name='الحاله الصحيه')
    status = models.CharField(max_length=255, null=True, blank=True, verbose_name='الحالة الاجتماعية')
    age = models.SmallIntegerField(null=True, verbose_name='العمر')
    data_added = models.DateField(auto_now_add=True, null=True)
    case_number = models.SmallIntegerField(null=True, blank=True)
    emp_name = models.CharField(null=True, max_length=255, verbose_name='اسم المشرف')
    support = models.SmallIntegerField(null=True, max_length=255, verbose_name='الدعم المقدم', choices=CASES_CHOICES)
    department = models.CharField(null=True, max_length=255, verbose_name='المنطقة')
    amount = models.IntegerField(null=True, max_length=255, verbose_name='قيمة الدعم')
    completed = models.BooleanField(default=False, null=True, blank=True)

    @property
    def is_past_due(self):
        return self.completed

    def __str__(self):
        return self.name


class Foundation(models.Model):
    name = models.CharField(max_length=255, null=True, verbose_name='اسم المؤسسه')
    address = models.CharField(max_length=255, null=True, verbose_name='العنوان')
    phone = models.CharField(max_length=255, null=True, verbose_name='الجوال')
    description = models.CharField(max_length=255, null=True, verbose_name='عن المؤسسه')
    cases = models.ManyToManyField(Needy, related_name='case', verbose_name='الحالات', null=True)
    employee = models.ManyToManyField(User, related_name='employee', null=True, verbose_name='مشرفيين')

    def __str__(self):
        return self.name


class Provider(models.Model):
    name = models.CharField(max_length=255, null=True, verbose_name='اسم الراعى')
    address = models.CharField(max_length=255, null=True, verbose_name='العنوان')
    phone = models.CharField(max_length=255, null=True, verbose_name='الجوال')
    description = models.CharField(max_length=255, null=True, verbose_name='عن المؤسسه')
    employee = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Courses(models.Model):
    name = models.CharField(max_length=255, null=True, verbose_name='اسم الدوره')
    description = models.CharField(max_length=255, null=True, verbose_name='عن الدوره')
    provider = models.ForeignKey(Provider, null=True, on_delete=models.CASCADE, verbose_name='الراعى')
    start_date = models.DateField(verbose_name="تاريخ البدايه", null=True, auto_now=False, auto_now_add=False)
    end_date = models.DateField(verbose_name="تاريخ النهايه", null=True, auto_now=False, auto_now_add=False, )
    price = models.IntegerField(null=True, blank=True, verbose_name='السعر')
    TAMKEEN = (
        (1, 'تمكين منتهى بمقابل مادى'),
        (2, 'تمكين منتهى بتوظيف')
    )
    tamkeen = models.SmallIntegerField(null=True, blank=True, choices=TAMKEEN)

    @property
    def is_past_due(self):
        return date.today() > self.end_date

    def __str__(self):
        return self.name


class GreenParticipant(models.Model):
    participant = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='المشارك')
    foundation = models.ForeignKey(Foundation, on_delete=models.CASCADE, verbose_name='المؤسسه')
    provider = models.ForeignKey(Provider, blank=True, null=True, on_delete=models.CASCADE, verbose_name='الداعم')
    date_added = models.DateTimeField(auto_now_add=True, verbose_name='تاريخ اﻷضافه')

    def __str__(self):
        return self.foundation.name


class CourseBag(models.Model):
    name = models.CharField(max_length=255, null=True, verbose_name='اسم الدوره')
    description = models.CharField(max_length=255, null=True, verbose_name='عن الدوره')
    logo = models.ImageField(verbose_name='لوجو الدوره', null=True)
    duration = models.SmallIntegerField(null=True, blank=True)

    link = models.URLField(
        verbose_name='المسار',
        max_length=128,
        db_index=True,
        unique=True,
        blank=True,
        null=True
    )
    start_date = models.DateField(verbose_name="تاريخ البدايه", null=True, auto_now=False, auto_now_add=False)
    end_date = models.DateField(verbose_name="تاريخ النهايه", null=True, auto_now=False, auto_now_add=False, )
    total_hours = models.IntegerField(null=True, blank=True, verbose_name='عدد الساعات')
    trainer = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='المدرب')
    green = models.ManyToManyField(GreenParticipant, verbose_name='المشاركين', null=True, blank=True)
    foundation = models.ForeignKey(Foundation, null=True, blank=True, on_delete=models.CASCADE, verbose_name='المؤسسه')

    @property
    def is_past_due(self):
        return date.today() > self.end_date

    def __str__(self):
        return self.name


class PaymentCourseBag(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='المستخدم')
    course = models.ForeignKey(CourseBag, on_delete=models.CASCADE, verbose_name='الحقيبه')
    needy = models.ForeignKey(Needy, on_delete=models.CASCADE, verbose_name='المستفيد')

    def __str__(self):
        return self.user.first_name


class PayDonation(models.Model):
    amount = models.IntegerField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='المساهم')
    needy = models.ForeignKey(Needy, on_delete=models.CASCADE, null=True, blank=True, verbose_name='المساهم')

    def __str__(self):
        return self.needy.name


class PayTicket(models.Model):
    needy = models.OneToOneField(Needy, on_delete=models.CASCADE, verbose_name='المستفيد')
    ticket = models.FileField(verbose_name='سند الصرف', null=True, blank=True)

    def __str__(self):
        return self.needy.name


class BagCertificate(models.Model):
    bag = models.ForeignKey(Courses, on_delete=models.CASCADE, null=True, verbose_name='الحقيبه')
    needy = models.ForeignKey(Needy, on_delete=models.CASCADE, null=True, verbose_name='المستفيد')
    certificate = models.FileField(null=True, blank=True, verbose_name='الشهاده')

    def __str__(self):
        return self.needy.name

office/templates/office/search-courses.html
{% extends 'main.html' %}
{% load static %}

{% block title %} خير السعوديه  {% endblock title %}

{% block content %}
    <div class="ftco-blocks-cover-1">
        <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
        {% if pk ==   1 %}
            <div class="site-section-cover overlay" data-stellar-background-ratio="0.5"
                 style="background-image: url('../../../static/images/banner_money_tamkeen.png')">
                <div class="container">
                    <div class="row align-items-center ">

                        <div class="col-md-5 mt-5 pt-5">
                            <span class="text-cursive h5 " style="color: #2D6D93"> خير السعوديه</span>
                            <h1 class="mb-3 font-weight-bold body-font"> تمكين منتهى بدعم مالى</h1>

                            <p><a href="{% url 'home-page' %}" class="text-white">الرئيسيه</a> <span
                                    class="mx-3">/</span>
                                <strong>تمكين منتهى بدعم مالى </strong></p>
                        </div>

                    </div>
                </div>
            </div>
        {% else %}
            <div class="site-section-cover overlay" data-stellar-background-ratio="0.5"
                 style="background-image: url('../../../static/images/banner_employer_tamkeen.png')">
                <div class="container">
                    <div class="row align-items-center ">

                        <div class="col-md-5 mt-5 pt-5">
                            <span class="text-cursive h5 " style="color: #2D6D93"> خير السعوديه</span>
                            <h1 class="mb-3 font-weight-bold body-font"> تمكين منتهى بتوظيف</h1>

                            <p><a href="{% url 'home-page' %}" class="text-white">الرئيسيه</a> <span
                                    class="mx-3">/</span>
                                <strong>تمكين منتهى بدعم يتوظيف </strong></p>
                        </div>

                    </div>
                </div>
            </div>

        {% endif %}
    </div>

    <div class="site-section">
    <div class="container">
        <div class="row">
            <center>
                <button class="btn btn-success body-font text-white" id="btn_Search"><i class="fa fa-search-plus"
                                                                                        aria-hidden="true"></i>
                </button>
            </center>
            <div id="search">
                <form>
                    {% csrf_token %}

                    {% for filed in myfilter.form %}


                        {{ filed }}
                    {% endfor %}
                    <button id="btn_sub_search" type="submit" class="btn btn-success body-font text-white">البحث
                    </button>
                </form>

            </div>
        </div>
        <hr/>
        <br/>
        <div class="row">
            {% for course in courses %}
                <div class="col-md-4">
                <div>
                    {% if course.is_past_due %}
                        <div class=" content cc back course_card"
                             style="background-image: url('../../../static/images/end_course.png');text-align: center;">
                    {% else %}
                        <div class=" content cc course_card">


                    {% endif %}
                    <div class="card_needy">
                        <img src="{% static 'images/logo.png' %}" class="img-fluid"/>
                    </div>
                    <div class="card_needy">
                        <div class="itemright">
                            <i aria-hidden="true" style="color:#2D6D93;" class="fa fa-book"></i>
                        </div>
                        <div class="itemleft">
                            <h4 class="body-font text-blue">{{ course.name }}</h4>
                        </div>
                    </div>


                    <div class="card_needy">
                        <div class="itemright">
                            <i aria-hidden="true" style="color:#2D6D93;" class="fa fa-calendar"></i>
                        </div>
                        <div class="itemleft">
                            <h4 class="body-font text-blue">{{ course.start_date }}</h4>
                        </div>
                    </div>
                    <div class="card_needy">
                        <div class="itemright">
                            <i aria-hidden="true" style="color:#2D6D93;" class="fa  fa-calendar"></i>
                        </div>
                        <div class="itemleft">
                            <h4 class="body-font text-blue">{{ course.end_date }}</h4>
                        </div>
                    </div>
                    <div class="card_needy">
                        <div class="itemright">
                            <img src="{% static 'images/motabr3.png' %}" style="width:30px; height:30px;"/>
                        </div>
                        <div class="itemleft">
                            <h4 class="body-font text-blue">{{ course.price }}</h4>
                        </div>
                    </div>
                    <div class="card_needy">
                        <div class="itemright">
                            <i aria-hidden="true" style="color:#2D6D93;" class="fa  fa-newspaper-o "></i>
                        </div>
                        <div class="itemleft">
                            <h4 class="body-font text-blue">{{ course.description }}</h4>
                        </div>
                    </div>

                    <div style="display:flex;  margin-top: 1.7rem">
                        <a class="btn btn-blue body-font" style="color:#ffffff; text-align: center; margin-top: 2rem; "
                           href="{% url 'tamkeen-course-pay' course.pk %}">مشاركة<i class="fa fa-share-alt" style="margin-inline: 0.4rem;
    font-size: large; margin-block: 0.2rem;" aria-hidden="true"></i>
                        </a>
                    </div>


                    </div>

                    </div>
                </div>


            {% endfor %}

            </div>
        </div>
    </div>


{% endblock content %}


{% block javascript %}
    <script>
        var search = false;
        $(() => {
            $("#search").hide();
            $("#id_start_date").addClass('form-control')
            $("#id_name").addClass('form-control body-font')
            $("#id_name").attr('placeholder', "بحث بأسم الدوره")
            $("#id_start_date").attr("type", "date");
            $("#id_start_date").attr("placeholder", "بحث بتاريخ البدايه");
            $("#id_end_date").attr("placeholder", "بحث بتاريخ النهايه");
            $("#id_end_date").attr("type", "date");
            $("#id_end_date").addClass('form-control ')
            $("#btn_Search").on("click", (e) => {
                e.preventDefault();
                if (search) {
                    $("#search").hide();
                    search = false
                } else {
                    $("#search").show();
                    search = true

                }
            });

        });
    </script>

{% endblock javascript %}

office/templates/office/search-needy.html
{% extends 'main.html' %}
{% load static %}

{% block title %}   خير السعوديه  {% endblock title %}

{% block content %}
   {% if pk == 1 %}
        <div class="ftco-blocks-cover-1">
        <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
        <div class="site-section-cover overlay" data-stellar-background-ratio="0.5"
             style="background-image: url('../../../static/images/search.png')">
            <div class="container">
                <div class="row align-items-center ">

                    <div class="col-md-5 mt-5 pt-5">
                        <span class="text-cursive h5 " style="color: #5DBD7E"> خير السعوديه</span>
                        <h1 class="mb-3 font-weight-bold body-font">دعم الكهرباء </h1>
                        <p><a href="{% url 'home-page' %}" class="text-white">الرئيسيه</a> <span class="mx-3">/</span>
                            <strong>دعم الكهرباء</strong></p>
                    </div>

                </div>
            </div>
        </div>
    </div>
       {% elif pk == 2 %}
        <div class="ftco-blocks-cover-1">
        <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
        <div class="site-section-cover overlay" data-stellar-background-ratio="0.5"
             style="background-image: url('../../../static/images/search.png')">
            <div class="container">
                <div class="row align-items-center ">

                    <div class="col-md-5 mt-5 pt-5">
                        <span class="text-cursive h5 " style="color: #5DBD7E"> خير السعوديه</span>
                        <h1 class="mb-3 font-weight-bold body-font">دعم الغذاء </h1>
                        <p><a href="{% url 'home-page' %}" class="text-white">الرئيسيه</a> <span class="mx-3">/</span>
                            <strong>دعم الغذاء</strong></p>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% elif pk == 3 %}
               <div class="ftco-blocks-cover-1">
        <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
        <div class="site-section-cover overlay" data-stellar-background-ratio="0.5"
             style="background-image: url('../../../static/images/search.png')">
            <div class="container">
                <div class="row align-items-center ">

                    <div class="col-md-5 mt-5 pt-5">
                        <span class="text-cursive h5 " style="color: #5DBD7E"> خير السعوديه</span>
                        <h1 class="mb-3 font-weight-bold body-font">دعم التعليم </h1>
                        <p><a href="{% url 'home-page' %}" class="text-white">الرئيسيه</a> <span class="mx-3">/</span>
                            <strong>دعم التعليم</strong></p>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% elif pk == 4  %}
               <div class="ftco-blocks-cover-1">
        <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
        <div class="site-section-cover overlay" data-stellar-background-ratio="0.5"
             style="background-image: url('../../../static/images/search.png')">
            <div class="container">
                <div class="row align-items-center ">

                    <div class="col-md-5 mt-5 pt-5">
                        <span class="text-cursive h5 " style="color: #5DBD7E"> خير السعوديه</span>
                        <h1 class="mb-3 font-weight-bold body-font">دعم الماء </h1>
                        <p><a href="{% url 'home-page' %}" class="text-white">الرئيسيه</a> <span class="mx-3">/</span>
                            <strong>دعم الماء</strong></p>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% elif pk == 5 %}
               <div class="ftco-blocks-cover-1">
        <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
        <div class="site-section-cover overlay" data-stellar-background-ratio="0.5"
             style="background-image: url('../../../static/images/search.png')">
            <div class="container">
                <div class="row align-items-center ">

                    <div class="col-md-5 mt-5 pt-5">
                        <span class="text-cursive h5 " style="color: #5DBD7E"> خير السعوديه</span>
                        <h1 class="mb-3 font-weight-bold body-font">دعم الصحة </h1>
                        <p><a href="{% url 'home-page' %}" class="text-white">الرئيسيه</a> <span class="mx-3">/</span>
                            <strong>دعم الصحة</strong></p>
                    </div>

                </div>
            </div>
        </div>
    </div>

       {% else%}
        <div class="ftco-blocks-cover-1">
        <!-- data-stellar-background-ratio="0.5" style="background-image: url('images/hero_1.jpg')" -->
        <div class="site-section-cover overlay" data-stellar-background-ratio="0.5"
             style="background-image: url('../../../static/images/search.png')">
            <div class="container">
                <div class="row align-items-center ">

                    <div class="col-md-5 mt-5 pt-5">
                        <span class="text-cursive h5 " style="color: #5DBD7E"> خير السعوديه</span>
                        <h1 class="mb-3 font-weight-bold body-font">دعم اﻷيجار </h1>
                        <p><a href="{% url 'home-page' %}" class="text-white">الرئيسيه</a> <span class="mx-3">/</span>
                            <strong>دعم اﻷيجار</strong></p>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endif %}
    <div class="site-section">
        <div class="container">
            <div class="row">
                <center>
                    <button class="btn btn-success body-font text-white" id="btn_Search"><i class="fa fa-search-plus"
                                                                                            aria-hidden="true"></i>
                    </button>
                </center>
                <div id="search">
                    <form>
                        {% csrf_token %}

                        {% for filed in myfilter.form %}


                            {{ filed }}
                        {% endfor %}
                        <button id="btn_sub_search" type="submit" class="btn btn-success body-font text-white">البحث
                        </button>
                    </form>

                </div>
            </div>
            <hr/>
            <br/>
            <div class="row">
                {% for need in neeedies %}
                    <div class="col-lg-4">
                    {% if need.is_past_due %}
                                                <div class="course_card content cc end_pay" style="background-image: url('../../../static/images/end_pay.png');" >

                        {% else %}
                                                <div class="course_card content cc">


                        {% endif %}
                            <div class="card_needy">
                                <div class="itemright">
                                    <i aria-hidden="true" style="color:#5DBD7E;" class="fa fa-user"></i>
                                </div>
                                <div class="itemleft">
                                    <h4 class="body-font text-green">{{ need.case_number }}</h4>
                                </div>
                            </div>
                            <div class="card_needy">
                                <div class="itemright">
                                    <i aria-hidden="true" style="color:#5DBD7E;" class="fa  fa-blind"></i>
                                </div>
                                <div class="itemleft">
                                    <h4 class="body-font text-green">{{ need.health_status }}</h4>
                                </div>
                            </div>
                            <div class="card_needy">
                                <div class="itemright">
                                    <i aria-hidden="true" style="color:#5DBD7E;" class="fa fa-home "></i>
                                </div>
                                <div class="itemleft">
                                    <h4 class="body-font text-green">{{ need.home }}</h4>
                                </div>
                            </div>
                            <div class="card_needy">
                                <div class="itemright">
                                    <i aria-hidden="true" style="color:#5DBD7E;" class="fa  fa-hand-paper-o "></i>
                                </div>
                                <div class="itemleft">
                                    <h4 class="body-font text-green">{{ need.job }}</h4>
                                </div>
                            </div>
                            <div class="card_needy">
                                <div class="itemright">
                                    <i aria-hidden="true" style="color:#5DBD7E;" class="fa  fa-newspaper-o "></i>
                                </div>
                                <div class="itemleft">
                                    <h4 class="body-font text-green">{{ need.source_income }}</h4>
                                </div>
                            </div>
                            <div class="card_needy">
                                <div class="itemright">
                                    <i aria-hidden="true" style="color:#5DBD7E;" class="fa  fa-map-marker "></i>
                                </div>
                                <div class="itemleft">
                                    <h4 class="body-font text-green">{{ need.department }}</h4>
                                </div>
                            </div>
                            <div class="card_needy">
                                <div class="itemright">
                                    <img src="{% static 'images/coins.png' %}" style="width:30px; height:30px;"/>
                                </div>
                                <div class="itemleft">
                                    <h4 class="body-font text-green">{{ need.amount }}</h4>
                                </div>
                            </div>
                            <div style="display:flex; align-items:center; justify-content:center; align-self: center; border-radius: 50px;">
                                <a class="btn-sm btn-success body-font" style="color:#ffffff; text-align: center;"
                                   href="{% url 'needy-payment' need.pk %}">دعم</a>
                            </div>


                        </div>
                    </div>


                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}


{% block javascript %}
    <script>
        var search = false;
        $(() => {
            $("#search").hide();
            $("#id_source_income").addClass('form-control body-font')
            $("#id_home").addClass('form-control body-font')
            $("#id_name").addClass('form-control body-font')
            $("#id_health_status").addClass('form-control body-font')
            $("#id_name_part").attr('placeholder', "بحث بجزء من الأسم ")
            $("#id_name_part").addClass('form-control body-font')

            $("#btn_Search").on("click", (e) => {
                e.preventDefault();
                if (search) {
                    $("#search").hide();
                    search = false
                } else {
                    $("#search").show();
                    search = true

                }
            });

        });
    </script>

{% endblock javascript %}